name: Consenso e Integridade da Rede
on:
  workflow_dispatch:
    inputs:
      block:
        description: 'JSON do Bloco Minerado'
        required: true

concurrency: 
  group: blockchain-consensus
  cancel-in-progress: false

jobs:
  validar-e-registrar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando Versão Oficial da Chain
        uses: actions/checkout@v4

      - name: Configurando Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodando o Validador de Consenso
        run: |
          # Compila o validador que você deixou na raiz
          javac -cp "lib/gson-2.11.0.jar" Validator.java
          # Executa o validador passando o bloco que o Java enviou
          java -cp "lib/gson-2.11.0.jar:." Validator '${{ github.event.inputs.block }}'

      - name: Salvando Novo Bloco no Ledger
        if: success()
        run: |
          git config user.name "Bot_de_Consenso"
          git config user.email "bot@blockchain.com"
          git add BlockChain.json
          git commit -m "Consenso: Bloco validado e anexado à rede"
          git push